language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_install:
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

install: composer install

cache:
  directories:
  - $HOME/.composer/cache/repo/
  - $TRAVIS_BUILD_DIR/vendor/

script:
  - vendor/bin/phpunit tests
  - vendor/bin/php-cs-fixer fix src
  - vendor/bin/php-cs-fixer fix tests

branches:
  only:
    - master

notifications:
  email:
    on_success: never
